inherit_gem:
  citizens-advice-style:
    - default.yml

AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 2.7.0

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 21

RSpec/DescribeClass:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
