inherit_gem:
  citizens-advice-style:
    - default.yml

AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.1

Capybara/ClickLinkOrButtonStyle:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Max: 21

RSpec/DescribeClass:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
