inherit_gem:
  citizens-advice-style:
    - default.yml

AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.2

Capybara/ClickLinkOrButtonStyle:
  Enabled: false

Metrics:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Performance/CollectionLiteralInLoop:
  Exclude:
    - spec/**/*
