# frozen_string_literal: true

require "capybara_accessible_selectors/selectors/alert"
require "capybara_accessible_selectors/selectors/article"
require "capybara_accessible_selectors/selectors/banner"
require "capybara_accessible_selectors/selectors/combo_box"
require "capybara_accessible_selectors/selectors/contentinfo"
require "capybara_accessible_selectors/selectors/dialog"
require "capybara_accessible_selectors/selectors/disclosure"
require "capybara_accessible_selectors/selectors/grid"
require "capybara_accessible_selectors/selectors/img"
require "capybara_accessible_selectors/selectors/main"
require "capybara_accessible_selectors/selectors/menu"
require "capybara_accessible_selectors/selectors/microdata"
require "capybara_accessible_selectors/selectors/modal"
require "capybara_accessible_selectors/selectors/navigation"
require "capybara_accessible_selectors/selectors/region"
require "capybara_accessible_selectors/selectors/rich_text"
require "capybara_accessible_selectors/selectors/section"
require "capybara_accessible_selectors/selectors/tab"
