# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-ruby
# https://github.com/ruby/setup-ruby

name: Test and lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['4.0', '3.4', '3.3']

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1.316.0
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
      - uses: browser-actions/setup-geckodriver@fac5b0424c584257f32cf12c5eb4ba86014c34f8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: geckodriver --version
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby-version }}
      - name: Run rubocop
        run: bundle exec rubocop
      - name: Run Chromium tests
        run: bundle exec rspec
      - name: Run Firefox tests
        run: DRIVER=selenium_headless bundle exec rspec
      - name: Run rack_test tests
        run: DRIVER=rack_test bundle exec rspec
